/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminCreateSelfServiceRecoveryLinkBody {
    /// Link Expires In  The recovery link will expire at that point in time. Defaults to the configuration value of `selfservice.flows.recovery.request_lifespan`.
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<String>,
    #[serde(rename = "identity_id")]
    pub identity_id: String,
}

impl AdminCreateSelfServiceRecoveryLinkBody {
    pub fn new(identity_id: String) -> AdminCreateSelfServiceRecoveryLinkBody {
        AdminCreateSelfServiceRecoveryLinkBody {
            expires_in: None,
            identity_id,
        }
    }
}


