/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JsonError : The standard Ory JSON API error format.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JsonError {
    #[serde(rename = "error")]
    pub error: Box<crate::models::GenericError>,
}

impl JsonError {
    /// The standard Ory JSON API error format.
    pub fn new(error: crate::models::GenericError) -> JsonError {
        JsonError {
            error: Box::new(error),
        }
    }
}


