/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Meta : This might include a label and other information that can optionally be used to render UIs.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Meta {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Box<crate::models::UiText>>,
}

impl Meta {
    /// This might include a label and other information that can optionally be used to render UIs.
    pub fn new() -> Meta {
        Meta {
            label: None,
        }
    }
}


