/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SelfServiceRecoveryLink {
    /// Recovery Link Expires At  The timestamp when the recovery link expires.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    /// Recovery Link  This link can be used to recover the account.
    #[serde(rename = "recovery_link")]
    pub recovery_link: String,
}

impl SelfServiceRecoveryLink {
    pub fn new(recovery_link: String) -> SelfServiceRecoveryLink {
        SelfServiceRecoveryLink {
            expires_at: None,
            recovery_link,
        }
    }
}


