/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SelfServiceLogoutUrl {
    /// LogoutURL can be opened in a browser to  format: uri
    #[serde(rename = "logout_url")]
    pub logout_url: String,
}

impl SelfServiceLogoutUrl {
    pub fn new(logout_url: String) -> SelfServiceLogoutUrl {
        SelfServiceLogoutUrl {
            logout_url,
        }
    }
}


