/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SubmitSelfServiceSettingsFlowWithProfileMethodBody : nolint:deadcode,unused



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitSelfServiceSettingsFlowWithProfileMethodBody {
    /// The Anti-CSRF Token  This token is only required when performing browser flows.
    #[serde(rename = "csrf_token", skip_serializing_if = "Option::is_none")]
    pub csrf_token: Option<String>,
    /// Method  Should be set to profile when trying to update a profile.
    #[serde(rename = "method")]
    pub method: String,
    /// Traits contains all of the identity's traits.
    #[serde(rename = "traits")]
    pub traits: serde_json::Value,
}

impl SubmitSelfServiceSettingsFlowWithProfileMethodBody {
    /// nolint:deadcode,unused
    pub fn new(method: String, traits: serde_json::Value) -> SubmitSelfServiceSettingsFlowWithProfileMethodBody {
        SubmitSelfServiceSettingsFlowWithProfileMethodBody {
            csrf_token: None,
            method,
            traits,
        }
    }
}


