/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitSelfServiceSettingsFlowWithPasswordMethodBody {
    /// CSRFToken is the anti-CSRF token
    #[serde(rename = "csrf_token", skip_serializing_if = "Option::is_none")]
    pub csrf_token: Option<String>,
    /// Method  Should be set to password when trying to update a password.
    #[serde(rename = "method")]
    pub method: String,
    /// Password is the updated password
    #[serde(rename = "password")]
    pub password: String,
}

impl SubmitSelfServiceSettingsFlowWithPasswordMethodBody {
    pub fn new(method: String, password: String) -> SubmitSelfServiceSettingsFlowWithPasswordMethodBody {
        SubmitSelfServiceSettingsFlowWithPasswordMethodBody {
            csrf_token: None,
            method,
            password,
        }
    }
}


