/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SubmitSelfServiceSettingsFlowWithOidcMethodBody : nolint:deadcode,unused



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitSelfServiceSettingsFlowWithOidcMethodBody {
    /// Flow ID is the flow's ID.  in: query
    #[serde(rename = "flow", skip_serializing_if = "Option::is_none")]
    pub flow: Option<String>,
    /// Link this provider  Either this or `unlink` must be set.  type: string in: body
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    /// Method  Should be set to profile when trying to update a profile.
    #[serde(rename = "method")]
    pub method: String,
    /// Unlink this provider  Either this or `link` must be set.  type: string in: body
    #[serde(rename = "unlink", skip_serializing_if = "Option::is_none")]
    pub unlink: Option<String>,
}

impl SubmitSelfServiceSettingsFlowWithOidcMethodBody {
    /// nolint:deadcode,unused
    pub fn new(method: String) -> SubmitSelfServiceSettingsFlowWithOidcMethodBody {
        SubmitSelfServiceSettingsFlowWithOidcMethodBody {
            flow: None,
            link: None,
            method,
            unlink: None,
        }
    }
}


