/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SubmitSelfServiceLogoutFlowWithoutBrowserBody : nolint:deadcode,unused



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitSelfServiceLogoutFlowWithoutBrowserBody {
    /// The Session Token  Invalidate this session token.
    #[serde(rename = "session_token")]
    pub session_token: String,
}

impl SubmitSelfServiceLogoutFlowWithoutBrowserBody {
    /// nolint:deadcode,unused
    pub fn new(session_token: String) -> SubmitSelfServiceLogoutFlowWithoutBrowserBody {
        SubmitSelfServiceLogoutFlowWithoutBrowserBody {
            session_token,
        }
    }
}


