/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SuccessfulSelfServiceSettingsWithoutBrowser : The Response for Settings Flows via API



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SuccessfulSelfServiceSettingsWithoutBrowser {
    #[serde(rename = "flow")]
    pub flow: Box<crate::models::SelfServiceSettingsFlow>,
    #[serde(rename = "identity")]
    pub identity: Box<crate::models::Identity>,
}

impl SuccessfulSelfServiceSettingsWithoutBrowser {
    /// The Response for Settings Flows via API
    pub fn new(flow: crate::models::SelfServiceSettingsFlow, identity: crate::models::Identity) -> SuccessfulSelfServiceSettingsWithoutBrowser {
        SuccessfulSelfServiceSettingsWithoutBrowser {
            flow: Box::new(flow),
            identity: Box::new(identity),
        }
    }
}


