/*
 * Ory Kratos
 *
 * Welcome to the Ory Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UiNode : Nodes are represented as HTML elements or their native UI equivalents. For example, a node can be an `<img>` tag, or an `<input element>` but also `some plain text`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UiNode {
    #[serde(rename = "attributes")]
    pub attributes: serde_json::Value,
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "messages")]
    pub messages: Vec<crate::models::UiText>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::Meta>,
    #[serde(rename = "type")]
    pub _type: String,
}

impl UiNode {
    /// Nodes are represented as HTML elements or their native UI equivalents. For example, a node can be an `<img>` tag, or an `<input element>` but also `some plain text`.
    pub fn new(attributes: serde_json::Value, group: String, messages: Vec<crate::models::UiText>, meta: crate::models::Meta, _type: String) -> UiNode {
        UiNode {
            attributes,
            group,
            messages,
            meta: Box::new(meta),
            _type,
        }
    }
}


